---
Style/Documentation:
  Exclude:
  - spec/**/*.rb

Lint/Eval:
  Exclude:
  - spec/**/*.rb

Style/ClassAndModuleChildren:
  Exclude:
  - spec/**/*.rb

Style/GlobalVars:
  Exclude:
  - Vagrantfile

Metrics/MethodLength:
  Max: 11
  Include:
  - spec/support/assertions.rb
