---
inherit_from: .rubocop_todo.yml

Style/Documentation:
  Exclude:
  - spec/**/*.rb

Lint/Eval:
  Exclude:
  - spec/**/*.rb

Style/ClassAndModuleChildren:
  Exclude:
  - spec/**/*.rb

Style/GlobalVars:
  Exclude:
  - Vagrantfile
